steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/parkirkan-repo/parkirkan-scan:$COMMIT_SHA', '.']
    timeout: 1200s  # 20 minutes timeout for AI model download

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/parkirkan-repo/parkirkan-scan:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'parkirkan-scan'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/parkirkan-repo/parkirkan-scan:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast2'  # Jakarta region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Remove this if you want authentication
      - '--memory'
      - '4Gi'  # AI models need more memory
      - '--cpu'
      - '2'    # AI models need more CPU
      - '--timeout'
      - '300'  # 5 minutes timeout for requests
      - '--concurrency'
      - '1'    # Process one request at a time due to heavy AI workload
      - '--max-instances'
      - '10'   # Limit instances to control costs
      - '--port'
      - '8080'

images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/parkirkan-repo/parkirkan-scan:$COMMIT_SHA'

# Build timeout
timeout: 1800s  # 30 minutes total timeout
